version: "3.9"

services:
  mysql_userManagerDatabase:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: userManagerDatabase
      MYSQL_USER: pasan
      MYSQL_PASSWORD: pasan
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - database

  mysql_rideManagerDatabase:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rideManagerDatabase
      MYSQL_USER: pasan
      MYSQL_PASSWORD: pasan
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - database

  mysql_locationManagerDatabase:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: locationManagerDatabase
      MYSQL_USER: pasan
      MYSQL_PASSWORD: pasan
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - database

  UberBackend:
    build:
      context: .
    container_name: UberBackend
    depends_on:
      - mysql
    ports:
      - "8081:8081"
    volumes:
      - .:/app
    networks:
      - database

networks:
  database:

volumes:
  mysql_data:
