version: "3.9"

services:
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: uber_database
      MYSQL_USER: pasan
      MYSQL_PASSWORD: pasan
    ports:
      - "9000:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - database

  uber_backend:
    build:
      context: .
    container_name: uber_backend
    depends_on:
      - mysql
    ports:
      - "8080:8081"
    volumes:
      - .:/app
    networks:
      - database

networks:
  database:

volumes:
  mysql_data:
