version: "3.9"

services:
  mysql_userManagerDatabase:
    image: mysql:8
    container_name: userManagerDatabase
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${USERMANAGER_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${USERMANAGER_PORT}:3306"
    volumes:
      - mysql_user_data:/var/lib/mysql
    networks:
      - userManagerNetwork
    
  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    environment:
      - KAFKA_KRAFT_MODE=true
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@localhost:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CFG_LOG_DIRS=/tmp/kraft-combined-logs
    ports:
      - "9092:9092"

  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"

  # mysql_rideManagerDatabase:
  #   image: mysql:8
  #   container_name: rideManagerDatabase
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  #     MYSQL_DATABASE: ${RIDEMANAGER_DB}
  #     MYSQL_USER: ${MYSQL_USER}
  #     MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  #   ports:
  #     - "${RIDEMANAGER_PORT}:3306"
  #   volumes:
  #     - mysql_ride_data:/var/lib/mysql
  #   networks:
  #     - rideManagerNetwork

  # mysql_locationManagerDatabase:
  #   image: mysql:8
  #   container_name: locationManagerDatabase
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  #     MYSQL_DATABASE: ${LOCATIONMANAGER_DB}
  #     MYSQL_USER: ${MYSQL_USER}
  #     MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  #   ports:
  #     - "${LOCATIONMANAGER_PORT}:3306"
  #   volumes:
  #     - mysql_location_data:/var/lib/mysql
  #   networks:
  #     - locationManagerNetwork

  UserManager:
    image: pasanaa/usermanager
    container_name: UserManager
    depends_on:
      - mysql_userManagerDatabase
      - kafka
    ports:
      - "${USERMANAGER_APP_PORT}:8081"
    volumes:
      - .:/app
    networks:
      - userManagerNetwork

  # RideManager:
  #   image: pasanaa/ridemanager
  #   container_name: RideManager
  #   depends_on:
  #     - mysql_rideManagerDatabase
  #   ports:
  #     - "${RIDEMANAGER_APP_PORT}:8081"
  #   volumes:
  #     - .:/app
  #   networks:
  #     - rideManagerNetwork

  # LocationManager:
  #   image: pasanaa/locationmanager
  #   container_name: LocationManager
  #   depends_on:
  #     - mysql_locationManagerDatabase
  #   ports:
  #     - "${LOCATIONMANAGER_APP_PORT}:8081"
  #   volumes:
  #     - .:/app
  #   networks:
  #     - locationManagerNetwork

networks:
  userManagerNetwork:
  # rideManagerNetwork:
  # locationManagerNetwork:

volumes:
  mysql_user_data:
  # mysql_ride_data:
  # mysql_location_data:
