FROM ubuntu:22.04

COPY docker/install_dependencies.sh /tmp/install_dependencies.sh
RUN bash /tmp/install_dependencies.sh && rm /tmp/install_dependencies.sh

WORKDIR /UberBackend
COPY . .

COPY entrypointUserManager.sh /entrypointUserManager.sh
RUN chmod +x /entrypointUserManager.sh

EXPOSE 8081

ENTRYPOINT ["/entrypointUserManager.sh"]
