FROM ubuntu:22.04

COPY docker/install_dependencies.sh /tmp/install_dependencies.sh
RUN bash /tmp/install_dependencies.sh && rm /tmp/install_dependencies.sh

WORKDIR /UberBackend
COPY . .

COPY entrypointLocationManager.sh /entrypointLocationManager.sh
RUN chmod +x /entrypointLocationManager.sh

EXPOSE 8083 50051

ENTRYPOINT ["/entrypointLocationManager.sh"]
