// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: location.proto
#ifndef GRPC_location_2eproto__INCLUDED
#define GRPC_location_2eproto__INCLUDED

#include "location.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace UberBackend {

class LocationService final {
 public:
  static constexpr char const* service_full_name() {
    return "UberBackend.LocationService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status SendLocation(::grpc::ClientContext* context, const ::UberBackend::UserLocation& request, ::UberBackend::LocationAck* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::UberBackend::LocationAck>> AsyncSendLocation(::grpc::ClientContext* context, const ::UberBackend::UserLocation& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::UberBackend::LocationAck>>(AsyncSendLocationRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::UberBackend::LocationAck>> PrepareAsyncSendLocation(::grpc::ClientContext* context, const ::UberBackend::UserLocation& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::UberBackend::LocationAck>>(PrepareAsyncSendLocationRaw(context, request, cq));
    }
    virtual ::grpc::Status GetNearbyUsers(::grpc::ClientContext* context, const ::UberBackend::NearbyRequest& request, ::UberBackend::NearbyUsers* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::UberBackend::NearbyUsers>> AsyncGetNearbyUsers(::grpc::ClientContext* context, const ::UberBackend::NearbyRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::UberBackend::NearbyUsers>>(AsyncGetNearbyUsersRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::UberBackend::NearbyUsers>> PrepareAsyncGetNearbyUsers(::grpc::ClientContext* context, const ::UberBackend::NearbyRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::UberBackend::NearbyUsers>>(PrepareAsyncGetNearbyUsersRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void SendLocation(::grpc::ClientContext* context, const ::UberBackend::UserLocation* request, ::UberBackend::LocationAck* response, std::function<void(::grpc::Status)>) = 0;
      virtual void SendLocation(::grpc::ClientContext* context, const ::UberBackend::UserLocation* request, ::UberBackend::LocationAck* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void GetNearbyUsers(::grpc::ClientContext* context, const ::UberBackend::NearbyRequest* request, ::UberBackend::NearbyUsers* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetNearbyUsers(::grpc::ClientContext* context, const ::UberBackend::NearbyRequest* request, ::UberBackend::NearbyUsers* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::UberBackend::LocationAck>* AsyncSendLocationRaw(::grpc::ClientContext* context, const ::UberBackend::UserLocation& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::UberBackend::LocationAck>* PrepareAsyncSendLocationRaw(::grpc::ClientContext* context, const ::UberBackend::UserLocation& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::UberBackend::NearbyUsers>* AsyncGetNearbyUsersRaw(::grpc::ClientContext* context, const ::UberBackend::NearbyRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::UberBackend::NearbyUsers>* PrepareAsyncGetNearbyUsersRaw(::grpc::ClientContext* context, const ::UberBackend::NearbyRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status SendLocation(::grpc::ClientContext* context, const ::UberBackend::UserLocation& request, ::UberBackend::LocationAck* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::UberBackend::LocationAck>> AsyncSendLocation(::grpc::ClientContext* context, const ::UberBackend::UserLocation& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::UberBackend::LocationAck>>(AsyncSendLocationRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::UberBackend::LocationAck>> PrepareAsyncSendLocation(::grpc::ClientContext* context, const ::UberBackend::UserLocation& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::UberBackend::LocationAck>>(PrepareAsyncSendLocationRaw(context, request, cq));
    }
    ::grpc::Status GetNearbyUsers(::grpc::ClientContext* context, const ::UberBackend::NearbyRequest& request, ::UberBackend::NearbyUsers* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::UberBackend::NearbyUsers>> AsyncGetNearbyUsers(::grpc::ClientContext* context, const ::UberBackend::NearbyRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::UberBackend::NearbyUsers>>(AsyncGetNearbyUsersRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::UberBackend::NearbyUsers>> PrepareAsyncGetNearbyUsers(::grpc::ClientContext* context, const ::UberBackend::NearbyRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::UberBackend::NearbyUsers>>(PrepareAsyncGetNearbyUsersRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void SendLocation(::grpc::ClientContext* context, const ::UberBackend::UserLocation* request, ::UberBackend::LocationAck* response, std::function<void(::grpc::Status)>) override;
      void SendLocation(::grpc::ClientContext* context, const ::UberBackend::UserLocation* request, ::UberBackend::LocationAck* response, ::grpc::ClientUnaryReactor* reactor) override;
      void GetNearbyUsers(::grpc::ClientContext* context, const ::UberBackend::NearbyRequest* request, ::UberBackend::NearbyUsers* response, std::function<void(::grpc::Status)>) override;
      void GetNearbyUsers(::grpc::ClientContext* context, const ::UberBackend::NearbyRequest* request, ::UberBackend::NearbyUsers* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::UberBackend::LocationAck>* AsyncSendLocationRaw(::grpc::ClientContext* context, const ::UberBackend::UserLocation& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::UberBackend::LocationAck>* PrepareAsyncSendLocationRaw(::grpc::ClientContext* context, const ::UberBackend::UserLocation& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::UberBackend::NearbyUsers>* AsyncGetNearbyUsersRaw(::grpc::ClientContext* context, const ::UberBackend::NearbyRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::UberBackend::NearbyUsers>* PrepareAsyncGetNearbyUsersRaw(::grpc::ClientContext* context, const ::UberBackend::NearbyRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_SendLocation_;
    const ::grpc::internal::RpcMethod rpcmethod_GetNearbyUsers_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status SendLocation(::grpc::ServerContext* context, const ::UberBackend::UserLocation* request, ::UberBackend::LocationAck* response);
    virtual ::grpc::Status GetNearbyUsers(::grpc::ServerContext* context, const ::UberBackend::NearbyRequest* request, ::UberBackend::NearbyUsers* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_SendLocation : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_SendLocation() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_SendLocation() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendLocation(::grpc::ServerContext* /*context*/, const ::UberBackend::UserLocation* /*request*/, ::UberBackend::LocationAck* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSendLocation(::grpc::ServerContext* context, ::UberBackend::UserLocation* request, ::grpc::ServerAsyncResponseWriter< ::UberBackend::LocationAck>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_GetNearbyUsers : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetNearbyUsers() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_GetNearbyUsers() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetNearbyUsers(::grpc::ServerContext* /*context*/, const ::UberBackend::NearbyRequest* /*request*/, ::UberBackend::NearbyUsers* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetNearbyUsers(::grpc::ServerContext* context, ::UberBackend::NearbyRequest* request, ::grpc::ServerAsyncResponseWriter< ::UberBackend::NearbyUsers>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_SendLocation<WithAsyncMethod_GetNearbyUsers<Service > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_SendLocation : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_SendLocation() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::UberBackend::UserLocation, ::UberBackend::LocationAck>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::UberBackend::UserLocation* request, ::UberBackend::LocationAck* response) { return this->SendLocation(context, request, response); }));}
    void SetMessageAllocatorFor_SendLocation(
        ::grpc::MessageAllocator< ::UberBackend::UserLocation, ::UberBackend::LocationAck>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::UberBackend::UserLocation, ::UberBackend::LocationAck>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_SendLocation() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendLocation(::grpc::ServerContext* /*context*/, const ::UberBackend::UserLocation* /*request*/, ::UberBackend::LocationAck* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SendLocation(
      ::grpc::CallbackServerContext* /*context*/, const ::UberBackend::UserLocation* /*request*/, ::UberBackend::LocationAck* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_GetNearbyUsers : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetNearbyUsers() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::UberBackend::NearbyRequest, ::UberBackend::NearbyUsers>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::UberBackend::NearbyRequest* request, ::UberBackend::NearbyUsers* response) { return this->GetNearbyUsers(context, request, response); }));}
    void SetMessageAllocatorFor_GetNearbyUsers(
        ::grpc::MessageAllocator< ::UberBackend::NearbyRequest, ::UberBackend::NearbyUsers>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::UberBackend::NearbyRequest, ::UberBackend::NearbyUsers>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetNearbyUsers() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetNearbyUsers(::grpc::ServerContext* /*context*/, const ::UberBackend::NearbyRequest* /*request*/, ::UberBackend::NearbyUsers* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetNearbyUsers(
      ::grpc::CallbackServerContext* /*context*/, const ::UberBackend::NearbyRequest* /*request*/, ::UberBackend::NearbyUsers* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_SendLocation<WithCallbackMethod_GetNearbyUsers<Service > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_SendLocation : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_SendLocation() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_SendLocation() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendLocation(::grpc::ServerContext* /*context*/, const ::UberBackend::UserLocation* /*request*/, ::UberBackend::LocationAck* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_GetNearbyUsers : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetNearbyUsers() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_GetNearbyUsers() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetNearbyUsers(::grpc::ServerContext* /*context*/, const ::UberBackend::NearbyRequest* /*request*/, ::UberBackend::NearbyUsers* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_SendLocation : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_SendLocation() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_SendLocation() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendLocation(::grpc::ServerContext* /*context*/, const ::UberBackend::UserLocation* /*request*/, ::UberBackend::LocationAck* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSendLocation(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetNearbyUsers : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetNearbyUsers() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_GetNearbyUsers() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetNearbyUsers(::grpc::ServerContext* /*context*/, const ::UberBackend::NearbyRequest* /*request*/, ::UberBackend::NearbyUsers* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetNearbyUsers(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_SendLocation : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_SendLocation() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->SendLocation(context, request, response); }));
    }
    ~WithRawCallbackMethod_SendLocation() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendLocation(::grpc::ServerContext* /*context*/, const ::UberBackend::UserLocation* /*request*/, ::UberBackend::LocationAck* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SendLocation(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetNearbyUsers : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetNearbyUsers() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetNearbyUsers(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetNearbyUsers() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetNearbyUsers(::grpc::ServerContext* /*context*/, const ::UberBackend::NearbyRequest* /*request*/, ::UberBackend::NearbyUsers* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetNearbyUsers(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_SendLocation : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_SendLocation() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::UberBackend::UserLocation, ::UberBackend::LocationAck>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::UberBackend::UserLocation, ::UberBackend::LocationAck>* streamer) {
                       return this->StreamedSendLocation(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_SendLocation() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status SendLocation(::grpc::ServerContext* /*context*/, const ::UberBackend::UserLocation* /*request*/, ::UberBackend::LocationAck* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedSendLocation(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::UberBackend::UserLocation,::UberBackend::LocationAck>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetNearbyUsers : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetNearbyUsers() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::UberBackend::NearbyRequest, ::UberBackend::NearbyUsers>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::UberBackend::NearbyRequest, ::UberBackend::NearbyUsers>* streamer) {
                       return this->StreamedGetNearbyUsers(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetNearbyUsers() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetNearbyUsers(::grpc::ServerContext* /*context*/, const ::UberBackend::NearbyRequest* /*request*/, ::UberBackend::NearbyUsers* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetNearbyUsers(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::UberBackend::NearbyRequest,::UberBackend::NearbyUsers>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_SendLocation<WithStreamedUnaryMethod_GetNearbyUsers<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_SendLocation<WithStreamedUnaryMethod_GetNearbyUsers<Service > > StreamedService;
};

}  // namespace UberBackend


#endif  // GRPC_location_2eproto__INCLUDED
