name: Build and Run Docker Compose

on:
  push:
    branches:
      - main
jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub (optional)
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build base image
      run: |
        docker build -f docker/Dockerfile.base -t uber-base .

    - name: Build userManager image
      run: |
        docker build -f docker/Dockerfile.userManager -t usermanager .

    - name: Build rideManager image
      run: |
        docker build -f docker/Dockerfile.rideManager -t ridemanager .

    - name: Build locationManager image
      run: |
        docker build -f docker/Dockerfile.locationManager -t locationmanager .

    - name: Run docker-compose
      run: |
        docker-compose -f docker/docker-compose.yml up -d
