name: Docker Images CI

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Validate DockerHub credentials
        run: |
          if [ -z "${DOCKERHUB_USERNAME}" ] || [ -z "${DOCKERHUB_TOKEN}" ]; then
            echo "DockerHub credentials are required to build and push images." >&2
            exit 1
          fi

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Build and push service images
        env:
          DOCKERHUB_USERNAME: ${{ env.DOCKERHUB_USERNAME }}
        run: |
          set -euo pipefail
          while read -r dockerfile image_name; do
            tag="${DOCKERHUB_USERNAME}/${image_name}:latest"
            echo "Building ${tag} from ${dockerfile}"
            docker build -f "${dockerfile}" -t "${tag}" .
            docker push "${tag}"
          done <<'EOF'
docker/Dockerfile.base uber-base
docker/Dockerfile.UserManager usermanager
docker/Dockerfile.RideManager ridemanager
docker/Dockerfile.LocationManager locationmanager
EOF
